org.gradle.jvmargs=-Xmx3G -Dnet.minecraftforge.gradle.check.certs=false
org.gradle.daemon=false

# Minecraft
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

# Forge
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

# Mappings
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

# SanSystem Mod
mod_id=san_system
mod_version=1.0.0_Beta
mod_group_id=com.restone.sansystem

# SanSystem mods.toml
mod_name=SanSystem
mod_license=All Rights Reserved
mod_authors=Restone
mod_description=None